
### Send SMS to login
POST https://app.sberfood.ru/api/mobile/v3/auth/sendSms
AppKey: WebApp-3a2605b0cf2a4c9d938752a84b7e97b6
AppPlatform: Web
AppVersion: 1
Content-Type: application/json;charset=UTF-8

{"userPhone":"{{phone}}"}

### Confirm login
POST https://app.sberfood.ru/api/mobile/v3/auth/checkSms
AppKey: WebApp-3a2605b0cf2a4c9d938752a84b7e97b6
AppPlatform: Web
AppVersion: 1
Content-Type: application/json;charset=UTF-8

{"userPhone":"{{phone}}","password":"9376"}

### Getting wallet
GET https://app.sberfood.ru/api/mobile/v3/user/{{userId}}/wallets
Accept: application/json
AppKey: WebApp-3a2605b0cf2a4c9d938752a84b7e97b6
AppPlatform: Web
AppVersion: 1
Token: {{token}}

t: {{$timestamp}}
offset: 0

### Activate code
POST https://app.sberfood.ru/api/mobile/v3/order/activate
AppKey: WebApp-3a2605b0cf2a4c9d938752a84b7e97b6
AppPlatform: Web
AppVersion: 1
Token: {{token}}
Content-Type: application/json;charset=UTF-8

{"promoCode":"5619#3713","clientFeatures":["Split"],"userId":"{{userId}}"}

### Generate Code
POST https://app.sberfood.ru/api/mobile/v3/user/{{userId}}/generateCode
AppKey: WebApp-3a2605b0cf2a4c9d938752a84b7e97b6
AppPlatform: Web
AppVersion: 1
Token: {{token}}
